CREATE SCHEMA ALMEIDAJJ;
SET SEARCH_PATH TO ALMEIDAJJ, PUBLIC;

CREATE TABLE PLANOS (
    ID_PLANO SERIAL PRIMARY KEY,
    PERIODO VARCHAR(20),
    QTD_MESES INTEGER NOT NULL,
    CONSTRAINT UK_PLANOS_PERIODO UNIQUE (QTD_MESES)
);

CREATE TABLE GRADUACOES (
    ID_GRADUACAO SERIAL PRIMARY KEY,
    FAIXA VARCHAR(2) NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    CONSTRAINT UK_GRADUACOES_FAIXA UNIQUE (FAIXA)
);

CREATE TABLE ALUNOS (
    ID_ALUNO SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    ID_GRADUACAO INTEGER NOT NULL,
    SITUACAO VARCHAR(1) NOT NULL DEFAULT 'I',
    IC_ADMINISTRADOR VARCHAR(1) NOT NULL DEFAULT 'N',
    DT_PAGAMENTO DATE,
    ID_PLANO INTEGER NOT NULL,
    DT_EXPIRACAO_PLANO DATE,
    CONSTRAINT FK_ALUNOS_GRADUACOES FOREIGN KEY (ID_GRADUACAO) REFERENCES GRADUACOES (ID_GRADUACAO),
    CONSTRAINT FK_ALUNOS_PLANOS FOREIGN KEY (ID_PLANO) REFERENCES PLANOS (ID_PLANO),
    CONSTRAINT UK_ALUNOS_EMAIL UNIQUE (EMAIL)
);
CREATE INDEX IDX_ALUNOS_GRADUACAO ON ALUNOS (ID_GRADUACAO);
CREATE INDEX IDX_ALUNOS_PLANO ON ALUNOS (ID_PLANO);

CREATE TABLE AULAS (
    ID_AULA SERIAL PRIMARY KEY,
    HORARIO TIME NOT NULL,
    DTHR_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_AULAS_HORARIO UNIQUE (HORARIO)
);

CREATE TABLE PRESENCAS (
    ID_PRESENCA SERIAL PRIMARY KEY,
    ID_ALUNO INTEGER NOT NULL,
    ID_AULA INTEGER NOT NULL,
    DTHR_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_PRESENCA_ALUNO_IDAULA UNIQUE (ID_ALUNO, ID_AULA),
    CONSTRAINT FK_PRESENCAS_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO),
    CONSTRAINT FK_PRESENCAS_AULAS FOREIGN KEY (ID_AULA) REFERENCES AULAS (ID_AULA)
);

CREATE TABLE SCRIPT_UPDATE (
    ID_SCRIPT SERIAL PRIMARY KEY,
    VERSAO VARCHAR(10) NOT NULL,
    DH_INCL TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
